# Generated by Django 3.2.5 on 2021-07-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bgyoons',
            new_name='Bgyoon',
        ),
    ]
